### ISSUE TITLE
SSR compatibility with Nuxt 3

### ISSUE THREAD

**Issue by Maginobion** [intlify/vue-i18n-extensions#165]
Hello!

I'm working on a Nuxt 3 project using i18n and everything worked fine until I used this plugin for the v-t directive compatibility with SSR, and I wasn't able to replicate the config steps for it to work.

Could it be possible to make this plugin work with Nuxt 3?

Thanks in advance!

**Comment by kazupon** [comment]
Hello!
Sorry, my delay response 🙇 

Regarding Nuxt3's SSR, we don't need to use this package for it to work.
Because v-t directive is implemented in vue-i18n using `getSSRProps`.
https://vuejs.org/guide/scaling-up/ssr.html#custom-directives

If you have any problems, please give me a minimal reproduction repo or stackblirz at @nuxtjs/i18n repo
Thanks!
